### ISSUE TITLE
Maven repo release

### ISSUE THREAD

**Issue by matheusjardimb** [janheinrichmerker/material-singleinputform#1]
Just opened this issue to keep tracking of this action item :smiley: 

Please, close it when done.

Great job!

**Comment by bzkdjc** [comment]
From Android Studio 2.0 b5, after adding maven {...} to build.gradle
`Error:(25, 13) Failed to resolve: com.heinrichreimersoftware:material-singleinputform:2.0.2`

**Comment by bzkdjc** [comment]
OK. Not an issue. 
Only that 2.0.2 from README does not exist at repository.

**Comment by HeinrichReimer** [comment]
Just use the latest dependency via the jitpack badge.
